[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["@google-cloud/aiplatform"]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*.js"]

[functions.api]
  timeout = 120

[functions."*"]
  timeout = 120

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  [redirects.headers]
    Access-Control-Allow-Origin = "http://localhost:3001"
    Access-Control-Allow-Methods = "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#auto"
  port = 8888        # Port for Netlify Dev
  targetPort = 3001  # Port for your React app
  publish = "public"
  functions = "netlify/functions"
  command = "npm start"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  CI = "false"