[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*.js"]

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#auto"
  port = 8888
  targetPort = 3001
  publish = "build"
  functions = "netlify/functions"
  command = "npm start"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "9.8.1"
  CI = "false"